# frozen_string_literal: true

ruby "~> 3.3.0"
source "https://rubygems.org"

gem "atproto_auth", path: "../.."
gem "dotenv"
gem "faraday"
gem "json"
gem "puma"
gem "rackup"
gem "sinatra"
gem "sinatra-contrib"
