module AtprotoAuth
  module PKCE
    class Error < AtprotoAuth::Error
    end

    MIN_VERIFIER_LENGTH: Integer
    MAX_VERIFIER_LENGTH: Integer
    ALLOWED_VERIFIER_CHARS: ::Regexp

    def self.generate_verifier: (?Integer length) -> String

    def self.generate_challenge: (String verifier) -> String

    def self.verify: (String challenge, String verifier) -> bool

    private

    def self.validate_verifier_length!: (Integer length) -> void

    def self.validate_verifier!: (String verifier) -> void

    def self.secure_compare: (String str1, String str2) -> bool
  end
end
